# Generated by Django 3.2.16 on 2023-07-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_scannedcontents'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequelizeMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sequelizemeta',
            },
        ),
    ]
