# Generated by Django 3.2.16 on 2023-07-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_sequelizemeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('file_id', models.IntegerField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('polarity', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
    ]
