# Generated by Django 3.2.16 on 2023-07-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isDelete',
            field=models.BooleanField(default=True),
        ),
    ]
